### ISSUE TITLE
Feature request: Hop aroma profile 

### ISSUE THREAD

**Issue by kasperg3** [scheb/beer-analytics#145]
In this repository: https://github.com/kasperg3/HopDatabase
I have extracted hop data from beermaverick(WIP) and Hopsteiner, which contains aroma and flavor notes. It would be nice to be able to compare the different hop profiles using, for example, a radar chart, similar to beermaverick: https://beermaverick.com/hops/hop-comparison-tool/. 

Let me know what you think.

**Comment by scheb** [comment]
That's some great data that you've collected there!

I've been thinking about that myself before, but I decided against integrating spider chart aroma profiles information into the page for several reasons:

1) I don't want to just take other people's work and put it on my page (in case of BeerMaverick; I wouldn't have such a problem with official information from the distributor, like Hopsteiner)
2) I don't want to do the exact same thing that other websites (i.e. BeerMaverick) are already doing quite well. I'd rather link out to related resources.
3) I personally don't think these aroma spider charts are much helpful. They look great, but I don't remember when I ever got useful information out of such a chart 🤷. I believe the issue is, the aroma categories are simply to broad on such charts, that you _need_ to look at the aroma descriptors anyways. But that's my personal opinion :)

Though, what I would be interested in, using your extracted data from Hopsteiner to check if the list of substitutes and aroma descriptors for completeness. Would that be okay for you?

**Comment by kasperg3** [comment]
Hi, thank you for your answer. 

I understand your motivation for not having the spider chart, as there are other great tools for displaying the spider graph/radar chart. David Heath on YouTube recently did a video of using the hop comparison tool from another software, which is also where I got the idea initially: https://www.youtube.com/watch?v=Gzc-GPNl5aM&ab_channel=DavidHeathHomebrew
Regarding the aroma categories, I think you are right, different hop producers use different sensory analyses and have different aromas, and it would be very difficult to generalize between vendors. 

You are welcome to use the extracted data from Hopsteiner. I am currently also working on extracting information from Yakima Chief, which also seems straightforward. I will comment on this issue once I have created the scraper.

**Comment by kasperg3** [comment]
I have just created a scraper that fetches general information about the hops (aromas, alpha, beta, cohumulone, total oil):
[yakima_chief_hops.json](https://github.com/scheb/beer-analytics/files/14904685/hop_data.json)
[hopsteiner_hop_data.json](https://github.com/scheb/beer-analytics/files/14904687/hopsteiner_hop_data.json)

If I were to import the data into the beer-analytics, which formats should the hop data have? @scheb

**Comment by scheb** [comment]
The raw hops information is stored in this CSV, you could try to merge it with the scrapped data: https://github.com/scheb/beer-analytics/blob/main/recipe_db/data/hops.csv

It is processed/imported with the Django command "load_initial_data" into the database.

**Comment by kasperg3** [comment]
I have scraped more data from both Yakima chief,hopsteiner and Barth Haas and formatted it in a consistent way using json: https://github.com/kasperg3/HopDatabase/actions/runs/8613435847

I will close the issue here. 
When I get time, I will probably open a PR to add hop oil breakdown, to visualize the different oils in the hops. (This data is available in some of the scraped data)

**Comment by scheb** [comment]
Nice work! I'll look into that on the weekend.

**Comment by scheb** [comment]
Merged in the flavors. Thanks again for sharing, I added an acknowledgments section to the readme mentioning your project.

There are some new flavor descriptors now that I will eventually add pages for.
